### ISSUE TITLE
Sign assembly

### ISSUE THREAD

**Issue by kblok** [webdriverbidi-net/webdriverbidi-net#12]
We need to sign the assembly to prevent `1>CSC: Error CS8002 : Referenced assembly 'WebDriverBiDi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.` errors.

I know that strong names are not required a lot these days. But `puppeteer-sharp` was requested to use a strong name, and I would need `webdriverbidi-net` to have a strong name to add this as a dependency.

**Comment by jimevans** [comment]
@kblok That's totally fair. I'm researching how to create a key file, given that I only have MacOS as my development environment.

**Comment by jimevans** [comment]
Fixed in 652bbed
